author: Nuno Aguiar
scripts:
  posterase: ''
  postinstall: ''
  preerase: ''
  preinstall: ''
keywords:
  - nattrmon
  - attribute
  - monitor
  - attrmon
bugs:
  url: 'https://github.com/OpenAF/nAttrMon/issues'
repository:
  type: http
  url: 'https://raw.githubusercontent.com/OpenAF/nAttrMon/master'
description: Tool for RAID and solution functional monitoring.
name: nAttrMon
main: nattrmon.js
mainJob: ''
license: Apache 2.0 license
version: '20171229'
dependencies:
  openaf: '>=20171101'
files:
  - util/backupConfig.yaml
  - util/loadDB2Elastic.js
  - util/clean.yaml
  - config/objects.assets/noutputhttp/index.html
  - config/objects.assets/noutputhttp/now.html
  - config/objects.assets/noutputhttp/css/bootstrap.min.css
  - config/objects.assets/noutputhttp/css/nattrmon.css
  - config/objects.assets/noutputhttp/css/font-awesome.min.css
  - config/objects.assets/noutputhttp/css/bootstrap-theme.min.css
  - config/objects.assets/noutputhttp/js/angular.min.js
  - config/objects.assets/noutputhttp/js/nattrmon_js.js
  - config/objects.assets/noutputhttp/js/retina.min.js
  - config/objects.assets/noutputhttp/js/ie10-viewport-bug-workaround.js
  - config/objects.assets/noutputhttp/js/jquery.min.js
  - config/objects.assets/noutputhttp/js/bootstrap.min.js
  - config/objects.assets/noutputhttp/js/holder.min.js
  - config/objects.assets/noutputhttp/js/angular-animate.min.js
  - config/objects.assets/noutputhttp/dashboard.css
  - config/objects.assets/noutputhttp/history.html
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.svg
  - config/objects.assets/noutputhttp/fonts/FontAwesome.otf
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.woff
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.eot
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.ttf
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff2
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.ttf
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.svg
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.eot
  - config/inputs.disabled/js/00.init.js
  - config/inputs.disabled/js/11.OSInfo.js
  - config/inputs.disabled/js/41.fms.rulestatus.js
  - config/inputs.disabled/js/09.filesystemcount.js
  - config/inputs.disabled/js/10.filesystem.js
  - config/inputs.disabled/js/00.doc.js
  - config/inputs.disabled/js/13.ListDirFiles.js
  - config/inputs.disabled/js/12.ShellCmd.js
  - config/inputs.disabled/js/05.filesystemCount.js
  - config/inputs.disabled/js/22.fraud.snapshots.js
  - config/inputs.disabled/js/07.logErrorAgg.js
  - config/inputs.disabled/js/10.filesystemcount.js
  - config/inputs.disabled/yaml/01.ping.yaml
  - config/inputs.disabled/yaml/10.filesystem.yaml
  - config/inputs.disabled/yaml/04.db.appadm.yaml
  - config/inputs.disabled/yaml/12.shellCmd.yaml
  - config/inputs.disabled/yaml/10.filesystemcount.mobsubscribers.yaml
  - config/inputs.disabled/yaml/10.sessions.yaml
  - config/inputs.disabled/yaml/02.test.yaml
  - config/inputs.disabled/yaml/10.osinfo.yaml
  - config/inputs.disabled/yaml/03.semaphores.yaml
  - config/inputs.disabled/yaml/10.filesystemcount.fixed.yaml
  - config/inputs.disabled/yaml/09.memory.yaml
  - config/inputs.disabled/yaml/01.test.yaml
  - config/inputs.disabled/yaml/11.times.yaml
  - config/inputs.disabled/yaml/12.connections.yaml
  - config/objects/nInput_OSInfo.js
  - config/objects/nOutput_EmailWarnings.js
  - config/objects/nInput_EndPoints.js
  - config/objects/nOutput_H2.js
  - config/objects/nInput_Semaphores.js
  - config/objects/nOutput_Stdout.js
  - config/objects/nInput_Filesystem.js
  - config/objects/nOutput_Channels.js
  - config/objects/nInput_RAIDMemory.js
  - config/objects/nInput_AFPing.js
  - config/objects/nOutput_HTTP_JSON.js
  - config/objects/nInput_FMSRuleStatus.js
  - config/objects/nValidation_Semaphores.js
  - config/objects/nInput_Sessions.js
  - config/objects/nOutput_Oracle.js
  - config/objects/nOutput_Log.js
  - config/objects/nInput_FilesystemCount.js
  - config/objects/nValidation_AFPing.js
  - config/objects/nOutput_HTTP.js
  - config/objects/nValidation_Yellows.js
  - config/objects/nInput_RunningFlows.js
  - config/objects/nInput_LogErrorAgg.js
  - config/objects/nInput_IMMemory.js
  - config/objects/nInput_CBPMSemaphores.js
  - config/objects/nInput_Shell.js
  - config/objects/nValidation_Generic.js
  - config/objects/nInput_DB.js
  - config/validations/add_files_from_validations_disabled.dummy
  - config/validations.disabled/js/01.validatePing.js
  - config/validations.disabled/js/30.validateYellows.js
  - config/validations.disabled/js/03.validateSemaphores.js
  - config/validations.disabled/js/04.validateErrorFlows.js
  - config/validations.disabled/yaml/01.somebodyTouched.yaml
  - config/validations.disabled/yaml/01.validatePing.yaml
  - config/outputs.disabled/2.httpjson.js
  - config/outputs.disabled/00.init.js
  - config/outputs.disabled/js/09.channels.js
  - config/outputs.disabled/3.http.js
  - config/outputs.disabled/1.oracleoutput.js
  - config/outputs.disabled/5.emailWarnings.js
  - config/outputs.disabled/yaml/09.channels.yaml
  - config/outputs.disabled/yaml/02.httpjson.yaml
  - config/outputs.disabled/4.logFile.js
  - config/outputs.disabled/1.h2output.js
  - config/outputs/add_files_from_outputs_disabled.dummy
  - config/move_files_from_the_disabled_folders.dummy
  - config/inputs/add_files_from_inputs_disabled.dummy
  - .package.yaml
  - tests/nattrmonTester.js
  - tests/outputTest.yml
  - tests/unitTest.js
  - tests/inputDBTest.yml
  - tests/inputShellTest.yml
  - tests/unitTestYAML.js
  - README.md
  - .gitignore
  - lib/nattributes.js
  - lib/nattributevalue.js
  - lib/nwarnings.js
  - lib/nwarning.js
  - lib/nattribute.js
  - lib/nplug.js
  - lib/ninput.js
  - lib/nvalidation.js
  - lib/nmonitoredobject.js
  - lib/noutput.js
  - nattrmon.js
filesHash:
  util/backupConfig.yaml: f84a08a3c5c8aa50f5aa606585c1453901c20d84
  util/loadDB2Elastic.js: 190b68c03e71fa859df71429da4c31035f20ce94
  util/clean.yaml: fe4084af9f1f6c70ae594fa5e6bdbddbc6dacc05
  config/objects.assets/noutputhttp/index.html: c454af426dc25960d1a2992b6cac99e11881ea48
  config/objects.assets/noutputhttp/now.html: 8dc28c8f998a319561567c342aa46fc16974e459
  config/objects.assets/noutputhttp/css/bootstrap.min.css: ed29315e0ffb3f14382431f2724235bf67f44eb3
  config/objects.assets/noutputhttp/css/nattrmon.css: aae10531cb3de16311f0ecc9f5bb213b5a3ac80c
  config/objects.assets/noutputhttp/css/font-awesome.min.css: 05ea25bc9b3ac48993e1fee322d3bc94b49a6e22
  config/objects.assets/noutputhttp/css/bootstrap-theme.min.css: fc6b4268fbd57ad95d2b41a1d4d6866f222fbdb2
  config/objects.assets/noutputhttp/js/angular.min.js: d0e3fccc46957eeaaf5611075a2015b410b64725
  config/objects.assets/noutputhttp/js/nattrmon_js.js: 16029240edd06a1d54bf1baad40c0dbc466b3940
  config/objects.assets/noutputhttp/js/retina.min.js: da44a409a0907960a6526cf35807ecaf61059223
  config/objects.assets/noutputhttp/js/ie10-viewport-bug-workaround.js: b133cb4aaff8f32026190281d8a27456eace82b1
  config/objects.assets/noutputhttp/js/jquery.min.js: 7ed710bf2b3a08cee23950790208683b0346fb1c
  config/objects.assets/noutputhttp/js/bootstrap.min.js: 253711c6d825de55a8360552573be950da180614
  config/objects.assets/noutputhttp/js/holder.min.js: c1ad1dcfebf4c1770d40fc5d7bc46ca692d12822
  config/objects.assets/noutputhttp/js/angular-animate.min.js: 648e2ca79c0c074b2b61042e91d31b353ad290d3
  config/objects.assets/noutputhttp/dashboard.css: 96d9d77e456868b0797afe0ce344be026315d535
  config/objects.assets/noutputhttp/history.html: aac6be153b65c31424a2b0e33b772b2e129fe76b
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.svg: 2b3c8ba7008cc014d8fb37abc6f9f49aeda83824
  config/objects.assets/noutputhttp/fonts/FontAwesome.otf: 0112e96f327d413938d37c1693806f468ffdbace
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.woff: 278e49a86e634da6f2a02f3b47dd9d2a8f26210f
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.eot: 86b6f62b7853e67d3e635f6512a5a5efc58ea3c3
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.ttf: 44bc1850f570972267b169ae18f1cb06b611ffa2
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff2: 574ea2698c03ae9477db2ea3baf460ee32f1a7ea
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.ttf: 27cf1f2ec59aece6938c7bb2feb0e287ea778ff9
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff: 507970402e328b2baeb05bde73bf9ded4e2c3a2d
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.svg: de51a8494180a6db074af2dee2383f0a363c5b08
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.eot: b3c2f08e73320135b69c23a3908b87a12053a2f6
  config/inputs.disabled/js/00.init.js: 0156834a9dd44c3685f2de871a6c84f78d631fa5
  config/inputs.disabled/js/11.OSInfo.js: ff6d21332af1722b09a3cce062876a1b5e5b0eef
  config/inputs.disabled/js/41.fms.rulestatus.js: 5b3012d798f11d2c82a633b3e54f5d6dc53614ad
  config/inputs.disabled/js/09.filesystemcount.js: 21ae3c36036bfaa0f786e73e9e862978727401df
  config/inputs.disabled/js/10.filesystem.js: 23a492c93be89b7be4163169f581c28dd85ab502
  config/inputs.disabled/js/00.doc.js: f03eb7b9bd36452d412d3668b0a4ef9c7605de65
  config/inputs.disabled/js/13.ListDirFiles.js: a5553247493a4039839d584c5cf590765429f3e2
  config/inputs.disabled/js/12.ShellCmd.js: eba2f60ed7c7e14a7340bd25fa8720eb1d12c026
  config/inputs.disabled/js/05.filesystemCount.js: 1a75ceb882dc94b03b9f05f696a7292cc9216ca3
  config/inputs.disabled/js/22.fraud.snapshots.js: eb5d52a7b57dece7331c2c9bbe612bc8cda8433e
  config/inputs.disabled/js/07.logErrorAgg.js: 924ca27ea2017cefa6550810bfcf216652597180
  config/inputs.disabled/js/10.filesystemcount.js: a1ae5183c585f082779e403c5f4b87dcc2c3a0f6
  config/inputs.disabled/yaml/01.ping.yaml: 9ba4d3140e53cc501f2fe8def5cbe42e96c61331
  config/inputs.disabled/yaml/10.filesystem.yaml: 3bc5c83e08464f9789f42161801fef768c7f2f3b
  config/inputs.disabled/yaml/04.db.appadm.yaml: 92a832c9ff134246aa889e2702f21085e28ccfda
  config/inputs.disabled/yaml/12.shellCmd.yaml: 0add6dbaa328f63e3ad864db9686bd98e1b3c2cf
  config/inputs.disabled/yaml/10.filesystemcount.mobsubscribers.yaml: 9996683cf2ba934c2b0dd2790ab953d7a05d6020
  config/inputs.disabled/yaml/10.sessions.yaml: 94c2ae34e45bf31f7efd979bddb60ac90348e2a3
  config/inputs.disabled/yaml/02.test.yaml: c67b289f6fb904cbf0167908b8af3a39780879b7
  config/inputs.disabled/yaml/10.osinfo.yaml: da7b6da3e3662b77917ccba2ebb008e36cdf89d6
  config/inputs.disabled/yaml/03.semaphores.yaml: 1c261bc2608c062f7e2299c7c0166d4548c7cf88
  config/inputs.disabled/yaml/10.filesystemcount.fixed.yaml: 168a63748db3a66fffeaa3e8c518e2ae4f123de4
  config/inputs.disabled/yaml/09.memory.yaml: f79360180738e0851b9bccbbdae1b6a7bccd052e
  config/inputs.disabled/yaml/01.test.yaml: 9da08f1b20136cfc092f37b386810ce7497ba509
  config/inputs.disabled/yaml/11.times.yaml: 0d2c1bfb7bd2f3160840b9aad98cd03e1cf68080
  config/inputs.disabled/yaml/12.connections.yaml: 691345117ddd695b5493127dea0a5568a8283fe9
  config/objects/nInput_OSInfo.js: 3418957f8d9e4d47dba8dd1100d0d101337904b3
  config/objects/nOutput_EmailWarnings.js: efde17d1a4704319a2783e4995c3643e06d5f232
  config/objects/nInput_EndPoints.js: 03084acddad1d42bd447ab5890dadac629681f96
  config/objects/nOutput_H2.js: 9f231c207510afc896de968eee3bdc3db558dd77
  config/objects/nInput_Semaphores.js: d837eae50410502438f9d2671bb5d52fb493e42b
  config/objects/nOutput_Stdout.js: 5a0d72c32e2f969fe3e27cbad64c7ccf0959aad1
  config/objects/nInput_Filesystem.js: 4117c1a9b19df25d80ce23b69782ff85bd131da7
  config/objects/nOutput_Channels.js: df08dc45f863dbb9744665ad83ebff2ea48368d1
  config/objects/nInput_RAIDMemory.js: bf7945d3af630132abf94f737524f38b8a4f74bd
  config/objects/nInput_AFPing.js: 1e39065380ba7c953533d31dc16ca3f3b0559562
  config/objects/nOutput_HTTP_JSON.js: 3ea3f20f79afcc498b4ecf19d3366cabd500730b
  config/objects/nInput_FMSRuleStatus.js: a5e4f9a505865b394a81ae4bbbdd839c91d07902
  config/objects/nValidation_Semaphores.js: 97b6c1850b80d95cc92c1c50b05fdfa26467fd94
  config/objects/nInput_Sessions.js: 0a68a945ba6c4b98d139b8c666c275c4fc716f81
  config/objects/nOutput_Oracle.js: ab0f2fe7958952437ae93030715633858462269f
  config/objects/nOutput_Log.js: 2a1d2d88a54b31b0fa1cece340c4a95ce8888476
  config/objects/nInput_FilesystemCount.js: daf3bd9806156dd16a0ac19692290d8b720fc0f9
  config/objects/nValidation_AFPing.js: 44117c2dd16882ff3d919e2f4f0eefcc05762263
  config/objects/nOutput_HTTP.js: 91453206bd740cb62fc2807e14b424de0110db2c
  config/objects/nValidation_Yellows.js: 942478fcd710e392add0b6ef6349ef51a895b764
  config/objects/nInput_RunningFlows.js: f21d3f64fc10348a5f7297aeae439c25bc5c68f0
  config/objects/nInput_LogErrorAgg.js: 149f6b0a61a806a0d3ffcf2975bb151f0a94317f
  config/objects/nInput_IMMemory.js: 1b3570cb3c64005c6b731f837c0684cd22cb5403
  config/objects/nInput_CBPMSemaphores.js: e22546f3b1de2b17d959c0fdbf0a35ea644c78ad
  config/objects/nInput_Shell.js: de4e651212ce678428caaa606fcec129b89a03bc
  config/objects/nValidation_Generic.js: 96bd3656e884a498451c83b25ebfdd6f1083d2f1
  config/objects/nInput_DB.js: 380121087bc0d77e18ffa0e9c9cc689c058ce184
  config/validations/add_files_from_validations_disabled.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/validations.disabled/js/01.validatePing.js: cc572c157971ebdccd0a40a261f199cb9e509b5c
  config/validations.disabled/js/30.validateYellows.js: 7a99fcd5e3728805783c5c18aff97488f3aed5d7
  config/validations.disabled/js/03.validateSemaphores.js: 6ded3ea530db8b5d4621fa8bad510e281ebd632d
  config/validations.disabled/js/04.validateErrorFlows.js: 9b7ff4c1cd03fe47082107d2c22250be1d45a2b4
  config/validations.disabled/yaml/01.somebodyTouched.yaml: 2d6a2c34c39aec49d9126c6304e04e66b978a26a
  config/validations.disabled/yaml/01.validatePing.yaml: 26a36f729f9443a1893afb7a8586fe7e396085db
  config/outputs.disabled/2.httpjson.js: f59875492834d2b24895bae73b51dfef3c38f49b
  config/outputs.disabled/00.init.js: 71ba0fb4fffa284500e9deb90213bfed66134568
  config/outputs.disabled/js/09.channels.js: 90b095b9c68e01b3aa724a8c370391f6d75cadf5
  config/outputs.disabled/3.http.js: 2c330262e3580992b79cacd0514bb2cdc6d1e17e
  config/outputs.disabled/1.oracleoutput.js: 0f7ce56148ba6772216ce4402f5509077c30af6e
  config/outputs.disabled/5.emailWarnings.js: 4a0139aabd64a3c56c1842499dd6d2203f607550
  config/outputs.disabled/yaml/09.channels.yaml: 99127166c4a2392fec5a0d681424bf61f68c0a95
  config/outputs.disabled/yaml/02.httpjson.yaml: 7c47a8c640dc9d8b8de10089ff2b90785d4eab9a
  config/outputs.disabled/4.logFile.js: 00ee44fa9c934d02beb6ec62b1aff6c473c14dbb
  config/outputs.disabled/1.h2output.js: a2dce3c2e443ca52f3344aca3529a17a064b3a51
  config/outputs/add_files_from_outputs_disabled.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/move_files_from_the_disabled_folders.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/inputs/add_files_from_inputs_disabled.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  tests/nattrmonTester.js: 72d94313ed4d69f0ec39a7d353a3edc723348248
  tests/outputTest.yml: 0c4ba4176163e4aa9ff7fd4ae4128339d8384581
  tests/unitTest.js: 067565f7c1517b331684246f5c9a7949124417ea
  tests/inputDBTest.yml: c38616606dc5956e449189d11f8e661170f94dfb
  tests/inputShellTest.yml: ce643955982cb16b53a8843acd3549466e5cddf5
  tests/unitTestYAML.js: 0fa75983c5b2af572891d6329fc18d10f7a47150
  README.md: 648ce4e29bbdc7b99f5cf8734cb1a7f0657789c7
  .gitignore: f7206c200c6c95e6ce56afc36f29f63106f16be6
  lib/nattributes.js: 35aa5c0dbda964c43dcf1d1b755d642f49d2d272
  lib/nattributevalue.js: d6a378dba74922540bcc3e054222733f69d5cead
  lib/nwarnings.js: 9b9f2cae8f0545650221a2fbceedf411708b61da
  lib/nwarning.js: 3bc36903e8e7f9be49b3f65352fe1dfddbe5b2aa
  lib/nattribute.js: 0eeb6849981672a5660811fb740327e8032211f5
  lib/nplug.js: 51f921822b4195de6cd949ea443c79fd64dce18b
  lib/ninput.js: cb1a2bc442a0a3ac9e6237fd02b445e31bd518cf
  lib/nvalidation.js: 649a184bf5a831647efb8b8de4f60f289c928ebd
  lib/nmonitoredobject.js: da0b8a8590ce1534826750e2e70b3d6e4bee9f98
  lib/noutput.js: 097a89ae2ab12cb28d88034444a72d368464d14c
  nattrmon.js: 9253eb82489e0e4dffe43f43223f397b33ca6742
