author: nuno.aguiar@wedotechnologies.com
scripts:
  posterase: ''
  postinstall: 'print(''AFPing: Since version 20160616 first parameter became URL.'');'
  preerase: ''
  preinstall: ''
keywords:
  - nattrmon
  - attribute
  - monitor
  - attrmon
bugs:
  url: 'https://github.com/OpenAF/nAttrMon/issues'
repository:
  type: http
  url: 'https://raw.githubusercontent.com/OpenAF/nAttrMon/master'
description: Tool for RAID and solution functional monitoring.
name: nAttrMon
main: nattrmon.js
mainJob: ''
license: Apache 2.0 license
version: '20171119'
dependencies:
  openaf: '>=20170901'
files:
  - .gitignore
  - .package.yaml
  - config/inputs/add_files_from_inputs_disabled.dummy
  - config/inputs.disabled/js/00.doc.js
  - config/inputs.disabled/js/00.init.js
  - config/inputs.disabled/js/05.filesystemCount.js
  - config/inputs.disabled/js/07.logErrorAgg.js
  - config/inputs.disabled/js/09.filesystemcount.js
  - config/inputs.disabled/js/10.filesystem.js
  - config/inputs.disabled/js/10.filesystemcount.js
  - config/inputs.disabled/js/11.OSInfo.js
  - config/inputs.disabled/js/12.ShellCmd.js
  - config/inputs.disabled/js/13.ListDirFiles.js
  - config/inputs.disabled/js/22.fraud.snapshots.js
  - config/inputs.disabled/js/41.fms.rulestatus.js
  - config/inputs.disabled/yaml/01.ping.yaml
  - config/inputs.disabled/yaml/01.test.yaml
  - config/inputs.disabled/yaml/02.test.yaml
  - config/inputs.disabled/yaml/03.semaphores.yaml
  - config/inputs.disabled/yaml/04.db.appadm.yaml
  - config/inputs.disabled/yaml/09.memory.yaml
  - config/inputs.disabled/yaml/10.filesystem.yaml
  - config/inputs.disabled/yaml/10.filesystemcount.fixed.yaml
  - config/inputs.disabled/yaml/10.filesystemcount.mobsubscribers.yaml
  - config/inputs.disabled/yaml/10.osinfo.yaml
  - config/inputs.disabled/yaml/10.sessions.yaml
  - config/inputs.disabled/yaml/11.times.yaml
  - config/inputs.disabled/yaml/12.connections.yaml
  - config/inputs.disabled/yaml/12.shellCmd.yaml
  - config/move_files_from_the_disabled_folders.dummy
  - config/objects/nInput_AFPing.js
  - config/objects/nInput_CBPMSemaphores.js
  - config/objects/nInput_DB.js
  - config/objects/nInput_Filesystem.js
  - config/objects/nInput_FilesystemCount.js
  - config/objects/nInput_FMSRuleStatus.js
  - config/objects/nInput_IMMemory.js
  - config/objects/nInput_LogErrorAgg.js
  - config/objects/nInput_OSInfo.js
  - config/objects/nInput_RAIDMemory.js
  - config/objects/nInput_RunningFlows.js
  - config/objects/nInput_Semaphores.js
  - config/objects/nInput_Sessions.js
  - config/objects/nInput_Shell.js
  - config/objects/nOutput_Channels.js
  - config/objects/nOutput_EmailWarnings.js
  - config/objects/nOutput_H2.js
  - config/objects/nOutput_HTTP.js
  - config/objects/nOutput_HTTP_JSON.js
  - config/objects/nOutput_Log.js
  - config/objects/nOutput_Oracle.js
  - config/objects/nOutput_Stdout.js
  - config/objects/nValidation_AFPing.js
  - config/objects/nValidation_Semaphores.js
  - config/objects/nValidation_Yellows.js
  - config/objects.assets/noutputhttp/css/bootstrap-theme.min.css
  - config/objects.assets/noutputhttp/css/bootstrap.min.css
  - config/objects.assets/noutputhttp/css/font-awesome.min.css
  - config/objects.assets/noutputhttp/css/nattrmon.css
  - config/objects.assets/noutputhttp/dashboard.css
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.eot
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.svg
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.ttf
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff
  - config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff2
  - config/objects.assets/noutputhttp/fonts/FontAwesome.otf
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.eot
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.svg
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.ttf
  - config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.woff
  - config/objects.assets/noutputhttp/history.html
  - config/objects.assets/noutputhttp/index.html
  - config/objects.assets/noutputhttp/js/angular-animate.min.js
  - config/objects.assets/noutputhttp/js/angular.min.js
  - config/objects.assets/noutputhttp/js/bootstrap.min.js
  - config/objects.assets/noutputhttp/js/holder.min.js
  - config/objects.assets/noutputhttp/js/ie10-viewport-bug-workaround.js
  - config/objects.assets/noutputhttp/js/jquery.min.js
  - config/objects.assets/noutputhttp/js/nattrmon_js.js
  - config/objects.assets/noutputhttp/js/retina.min.js
  - config/objects.assets/noutputhttp/now.html
  - config/outputs/add_files_from_outputs_disabled.dummy
  - config/outputs.disabled/00.init.js
  - config/outputs.disabled/1.h2output.js
  - config/outputs.disabled/1.oracleoutput.js
  - config/outputs.disabled/2.httpjson.js
  - config/outputs.disabled/3.http.js
  - config/outputs.disabled/4.logFile.js
  - config/outputs.disabled/5.emailWarnings.js
  - config/outputs.disabled/js/09.channels.js
  - config/outputs.disabled/yaml/02.httpjson.yaml
  - config/outputs.disabled/yaml/09.channels.yaml
  - config/validations/add_files_from_validations_disabled.dummy
  - config/validations.disabled/js/01.validatePing.js
  - config/validations.disabled/js/03.validateSemaphores.js
  - config/validations.disabled/js/04.validateErrorFlows.js
  - config/validations.disabled/js/30.validateYellows.js
  - config/validations.disabled/yaml/01.somebodyTouched.yaml
  - lib/nattribute.js
  - lib/nattributes.js
  - lib/nattributevalue.js
  - lib/ninput.js
  - lib/nmonitoredobject.js
  - lib/noutput.js
  - lib/nplug.js
  - lib/nvalidation.js
  - lib/nwarning.js
  - lib/nwarnings.js
  - nattrmon.js
  - README.md
  - tests/inputDBTest.yml
  - tests/inputShellTest.yml
  - tests/nattrmonTester.js
  - tests/outputTest.yml
  - tests/unitTest.js
  - tests/unitTestYAML.js
  - util/backupConfig.yaml
  - util/clean.yaml
  - util/loadDB2Elastic.js
filesHash:
  .gitignore: f7206c200c6c95e6ce56afc36f29f63106f16be6
  config/inputs/add_files_from_inputs_disabled.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/inputs.disabled/js/00.doc.js: f03eb7b9bd36452d412d3668b0a4ef9c7605de65
  config/inputs.disabled/js/00.init.js: 0156834a9dd44c3685f2de871a6c84f78d631fa5
  config/inputs.disabled/js/05.filesystemCount.js: 1a75ceb882dc94b03b9f05f696a7292cc9216ca3
  config/inputs.disabled/js/07.logErrorAgg.js: 924ca27ea2017cefa6550810bfcf216652597180
  config/inputs.disabled/js/09.filesystemcount.js: 21ae3c36036bfaa0f786e73e9e862978727401df
  config/inputs.disabled/js/10.filesystem.js: 23a492c93be89b7be4163169f581c28dd85ab502
  config/inputs.disabled/js/10.filesystemcount.js: a1ae5183c585f082779e403c5f4b87dcc2c3a0f6
  config/inputs.disabled/js/11.OSInfo.js: ff6d21332af1722b09a3cce062876a1b5e5b0eef
  config/inputs.disabled/js/12.ShellCmd.js: eba2f60ed7c7e14a7340bd25fa8720eb1d12c026
  config/inputs.disabled/js/13.ListDirFiles.js: 9ba182a6d286e5ac284828f24cb40ced8d36f0b9
  config/inputs.disabled/js/22.fraud.snapshots.js: eb5d52a7b57dece7331c2c9bbe612bc8cda8433e
  config/inputs.disabled/js/41.fms.rulestatus.js: 5b3012d798f11d2c82a633b3e54f5d6dc53614ad
  config/inputs.disabled/yaml/01.ping.yaml: 4099ba54ccf9a1cf7468b832205a97c77de01065
  config/inputs.disabled/yaml/01.test.yaml: dff4e9f6b3fe72619b6f360901e8d2d76f93c6b0
  config/inputs.disabled/yaml/02.test.yaml: f933560ac567b06c6b08327ff54e1bf1da5ca093
  config/inputs.disabled/yaml/03.semaphores.yaml: 9b2b96bf067585976ea84a805e528fd796331782
  config/inputs.disabled/yaml/04.db.appadm.yaml: 21473f76bd120810c87adc6bc9c7f25b74c51261
  config/inputs.disabled/yaml/09.memory.yaml: abd00277facadf9fa16f230fcb92dfee48bcd527
  config/inputs.disabled/yaml/10.filesystem.yaml: 8bb13a7aa3c03e9e0f613d3515401ee5d6f142f9
  config/inputs.disabled/yaml/10.filesystemcount.fixed.yaml: 1faa5c67efd1210e3905408f42a4e65ea96d3781
  config/inputs.disabled/yaml/10.filesystemcount.mobsubscribers.yaml: 7ed72797fc79f5ef67f3b7a175ab08bed702c9d4
  config/inputs.disabled/yaml/10.osinfo.yaml: 6b4782f7a307e447bb5ac9361da50ff0061029e0
  config/inputs.disabled/yaml/10.sessions.yaml: 5a1724db9eca8b90a6bb6310948a00d7909fc555
  config/inputs.disabled/yaml/11.times.yaml: f437adf46690615e0b52b7cd36eba2ba0eb1cff2
  config/inputs.disabled/yaml/12.connections.yaml: 72579273a36487c4fb05b546f49bec649d8f245f
  config/inputs.disabled/yaml/12.shellCmd.yaml: 30be1c8b7f3c0b2c9a089b6ea5d69e58413e8e98
  config/move_files_from_the_disabled_folders.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/objects/nInput_AFPing.js: 1e39065380ba7c953533d31dc16ca3f3b0559562
  config/objects/nInput_CBPMSemaphores.js: e22546f3b1de2b17d959c0fdbf0a35ea644c78ad
  config/objects/nInput_DB.js: 80437eeca4353ae8675bf9c35dba6a83bcf478ef
  config/objects/nInput_Filesystem.js: 4117c1a9b19df25d80ce23b69782ff85bd131da7
  config/objects/nInput_FilesystemCount.js: daf3bd9806156dd16a0ac19692290d8b720fc0f9
  config/objects/nInput_FMSRuleStatus.js: a5e4f9a505865b394a81ae4bbbdd839c91d07902
  config/objects/nInput_IMMemory.js: 1b3570cb3c64005c6b731f837c0684cd22cb5403
  config/objects/nInput_LogErrorAgg.js: 149f6b0a61a806a0d3ffcf2975bb151f0a94317f
  config/objects/nInput_OSInfo.js: 3418957f8d9e4d47dba8dd1100d0d101337904b3
  config/objects/nInput_RAIDMemory.js: bf7945d3af630132abf94f737524f38b8a4f74bd
  config/objects/nInput_RunningFlows.js: f21d3f64fc10348a5f7297aeae439c25bc5c68f0
  config/objects/nInput_Semaphores.js: d837eae50410502438f9d2671bb5d52fb493e42b
  config/objects/nInput_Sessions.js: 7c2d89a027fe0fa6478ab491484ce0d79fe27651
  config/objects/nInput_Shell.js: de4e651212ce678428caaa606fcec129b89a03bc
  config/objects/nOutput_Channels.js: ccf6d2ea993fde0a0db8c3af1431a8aef02b757a
  config/objects/nOutput_EmailWarnings.js: efde17d1a4704319a2783e4995c3643e06d5f232
  config/objects/nOutput_H2.js: 9f231c207510afc896de968eee3bdc3db558dd77
  config/objects/nOutput_HTTP.js: 91453206bd740cb62fc2807e14b424de0110db2c
  config/objects/nOutput_HTTP_JSON.js: 047a7086b8fd58ede9029a6832736de2e7c639cd
  config/objects/nOutput_Log.js: 2a1d2d88a54b31b0fa1cece340c4a95ce8888476
  config/objects/nOutput_Oracle.js: 93fa7228120945b1f1f6a7ecd8cf17853a4c6966
  config/objects/nOutput_Stdout.js: 5a0d72c32e2f969fe3e27cbad64c7ccf0959aad1
  config/objects/nValidation_AFPing.js: f7ce653012d15558088e50458adc415fa9792eaa
  config/objects/nValidation_Semaphores.js: 97b6c1850b80d95cc92c1c50b05fdfa26467fd94
  config/objects/nValidation_Yellows.js: 942478fcd710e392add0b6ef6349ef51a895b764
  config/objects.assets/noutputhttp/css/bootstrap-theme.min.css: c277f5dc2e08fa885e401ee367ac6c0eefa7a6dc
  config/objects.assets/noutputhttp/css/bootstrap.min.css: 12028adaae10f0c43445362df5481aeec8bb1153
  config/objects.assets/noutputhttp/css/font-awesome.min.css: 4c2c5f5f6cc86d775a44b944661e038b7be98149
  config/objects.assets/noutputhttp/css/nattrmon.css: f8a1827d3d8fd490023b8b472e3f8018af7e1d5a
  config/objects.assets/noutputhttp/dashboard.css: 9bab6b06cc427f9bd2908387e49e65f542c99764
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.eot: b3c2f08e73320135b69c23a3908b87a12053a2f6
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.svg: f346b8b3df147e4059e1a7d66c52c9a6e1cec3e8
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.ttf: 27cf1f2ec59aece6938c7bb2feb0e287ea778ff9
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff: 507970402e328b2baeb05bde73bf9ded4e2c3a2d
  config/objects.assets/noutputhttp/fonts/fontawesome-webfont.woff2: 574ea2698c03ae9477db2ea3baf460ee32f1a7ea
  config/objects.assets/noutputhttp/fonts/FontAwesome.otf: 0112e96f327d413938d37c1693806f468ffdbace
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.eot: 86b6f62b7853e67d3e635f6512a5a5efc58ea3c3
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.svg: 4dcf0ab896f5417047f881de91bad10dcbda48c6
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.ttf: 44bc1850f570972267b169ae18f1cb06b611ffa2
  config/objects.assets/noutputhttp/fonts/glyphicons-halflings-regular.woff: 278e49a86e634da6f2a02f3b47dd9d2a8f26210f
  config/objects.assets/noutputhttp/history.html: 2bac092a0b8be121592109c148cd35599bf0c083
  config/objects.assets/noutputhttp/index.html: 0f2297867ba6ea919039fe44864148973b6af819
  config/objects.assets/noutputhttp/js/angular-animate.min.js: 48ceb01a73169491d532151456b4004cb13446d8
  config/objects.assets/noutputhttp/js/angular.min.js: d2e5e39be85f51c828be35b20d877f6b4c101add
  config/objects.assets/noutputhttp/js/bootstrap.min.js: e2ddfe5a574c29f39b511aada1bd85e0ba60fa70
  config/objects.assets/noutputhttp/js/holder.min.js: c1ad1dcfebf4c1770d40fc5d7bc46ca692d12822
  config/objects.assets/noutputhttp/js/ie10-viewport-bug-workaround.js: f580bb4a182612f728cdef6ab2fd5e417879980b
  config/objects.assets/noutputhttp/js/jquery.min.js: b63bd0a78caf8effb1061adcde124376de49c607
  config/objects.assets/noutputhttp/js/nattrmon_js.js: fc1858030689c16e07f73c8ae255b9c81e855215
  config/objects.assets/noutputhttp/js/retina.min.js: db4bf8404dbd9900faada058ba0fdfeaf6aab23b
  config/objects.assets/noutputhttp/now.html: 85a1c9e3b010fde950f3c21b5d99e428f1b296f7
  config/outputs/add_files_from_outputs_disabled.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/outputs.disabled/00.init.js: 71ba0fb4fffa284500e9deb90213bfed66134568
  config/outputs.disabled/1.h2output.js: a2dce3c2e443ca52f3344aca3529a17a064b3a51
  config/outputs.disabled/1.oracleoutput.js: 0f7ce56148ba6772216ce4402f5509077c30af6e
  config/outputs.disabled/2.httpjson.js: f59875492834d2b24895bae73b51dfef3c38f49b
  config/outputs.disabled/3.http.js: 2c330262e3580992b79cacd0514bb2cdc6d1e17e
  config/outputs.disabled/4.logFile.js: 00ee44fa9c934d02beb6ec62b1aff6c473c14dbb
  config/outputs.disabled/5.emailWarnings.js: 4a0139aabd64a3c56c1842499dd6d2203f607550
  config/outputs.disabled/js/09.channels.js: 90b095b9c68e01b3aa724a8c370391f6d75cadf5
  config/outputs.disabled/yaml/02.httpjson.yaml: 7c47a8c640dc9d8b8de10089ff2b90785d4eab9a
  config/outputs.disabled/yaml/09.channels.yaml: 99127166c4a2392fec5a0d681424bf61f68c0a95
  config/validations/add_files_from_validations_disabled.dummy: da39a3ee5e6b4b0d3255bfef95601890afd80709
  config/validations.disabled/js/01.validatePing.js: cc572c157971ebdccd0a40a261f199cb9e509b5c
  config/validations.disabled/js/03.validateSemaphores.js: 6ded3ea530db8b5d4621fa8bad510e281ebd632d
  config/validations.disabled/js/04.validateErrorFlows.js: 9b7ff4c1cd03fe47082107d2c22250be1d45a2b4
  config/validations.disabled/js/30.validateYellows.js: 7a99fcd5e3728805783c5c18aff97488f3aed5d7
  config/validations.disabled/yaml/01.somebodyTouched.yaml: 2d6a2c34c39aec49d9126c6304e04e66b978a26a
  lib/nattribute.js: 4be29e971b5c0c23e1fc89f33d7ed6479d075809
  lib/nattributes.js: 4dc41e0d6fc25c1bdf16608ef41cad8d5df3506d
  lib/nattributevalue.js: f42b29f8b225a391cef31d7f3f22d41033aa3b96
  lib/ninput.js: af91b970f35098a561a187e93b7ec260d08ad934
  lib/nmonitoredobject.js: 24814b7ea819508162cac91a3dd7c14be801be96
  lib/noutput.js: 80983cb56a35eac3726a88e56cac9ea5d51cb39a
  lib/nplug.js: 5e5effd7342fdbc7600c2b283afcec01306d58fc
  lib/nvalidation.js: 27fac11ab81a5f2d289c89b9275a27d830a733fc
  lib/nwarning.js: b6ab4c67c583f878c95bbf19ee11b7099c132136
  lib/nwarnings.js: 939a814f4eb4d114ef22785ed877eb2ffb165e8e
  nattrmon.js: 4c419757f991561c482160938b426eadd48cae63
  README.md: b2a7dc80a439d865bd03d49960dbd6c96d02c254
  tests/inputDBTest.yml: acafbfa4233802897e81e9ee5457b06b76787303
  tests/inputShellTest.yml: 795c8479c1bfa93454b077d141f58161af5cae08
  tests/nattrmonTester.js: 0dc31695465dd13d73929a117e4d09a37be8d5fd
  tests/outputTest.yml: dade7c804e9f967eeb9016fcc045b943888b2ef0
  tests/unitTest.js: bf070ca62206b125a3530c1a34a6097f176b9756
  tests/unitTestYAML.js: 891879cd3b71d0d6351ae09af0886f981937c6bf
  util/backupConfig.yaml: 55d5cfebaf1acb87bd9ce2523015608b03f586e1
  util/clean.yaml: b1bbfd4a416313e02f6edc77ab8e956330834979
  util/loadDB2Elastic.js: caecf39b3afa1430c089ff57a9974d5bb10a06d9
